repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
        exclude: >
            (?x)^(
                charts|
                template.yaml
            )$
    -   id: check-added-large-files
        args: ['--maxkb=2000']
        exclude: post/utils/symspell
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.254'
  hooks:
    - id: ruff
      name: linting with Ruff 🐶
      args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        name: formatting files with black
- repo: https://github.com/python-poetry/poetry
  rev: '1.4.0'  # add version here
  hooks:
    - id: poetry-check
      name: validating poetry state