version: '3.8'
services:
  wiremock:
    container_name: juliet-wiremock-bff
    image: wiremock/wiremock:2.35.0
    command:
      - "--enable-stub-cors"
    volumes:
      - ./config/wiremock:/home/wiremock
    ports:
      - 8888:8080