version = 0.1
[default.deploy.parameters]
stack_name = "post-es-etl"
resolve_s3 = true
s3_prefix = "post-es-etl"
region = "us-east-1"
profile = "post-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ConsumerFunction=773663557741.dkr.ecr.us-east-1.amazonaws.com/postesetlab4dff55/consumerfunction4844f4cfrepo", "PDWDownloaderFunction=773663557741.dkr.ecr.us-east-1.amazonaws.com/postesetlab4dff55/pdwdownloaderfunction49626ae1repo", "ScoringFunction=773663557741.dkr.ecr.us-east-1.amazonaws.com/postesetlab4dff55/scoringfunctionefedb407repo"]

