server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          strictHostKeyChecking: false
          uri: git@github.com:morsco-reece/platform-configuration.git
          username: dialexa-reece-bot
          password: 91447c46f1d630f2fce1aef5ded5974564bbd3a7
management:
  endpoint:
    health:
      probes:
        enabled: true
