version: 2.1

parameters:
  environments-repo-chart-name:
    type: string
    default: "picking-core-service"

workflows:
  single-job-lifecycle:
    jobs:
      # - validate_helm_chart:
      #     filters:
      #       branches:
      #         ignore:
      #           - main
      # - maven/test:
      #     executor:
      #       name: maven/default
      #       tag: "17.0"
      # - java-services/validate_helm_chart:
      #     helm-chart-path: ./charts/picking-core-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         ignore:
      #           - main
      #           - /^release-v.*/
      # - java-services/publish_release:
      #     ecr-repo: reece/picking-core-service
      #     helm-chart-name: picking-core-service
      #     helm-chart-path: ./charts/picking-core-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         only: main
      # - java-services/publish_hotfix:
      #     ecr-repo: reece/picking-core-service
      #     helm-chart-name: picking-core-service
      #     helm-chart-path: ./charts/picking-core-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         only: /^release-v.*/
      # - deploy_to_dev:
      #     environments-repo-chart-name: picking-core-service
      #     requires:
      #       - java-services/publish_release
      #     filters:
      #       branches:
      #         only: main
      - sonar-cloud:
          context: SonarCloud
          # requires:
          #   - maven/test

jobs:
  # validate_helm_chart:
  #   executor: aws-cli/default
  #   steps:
  #     - checkout
  #     - aws-cli/setup:
  #         aws-access-key-id: AWS_ACCESS_KEY_ID
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #         aws-region: AWS_REGION
  #     - helm/install-helm-client:
  #         version: v3.3.4
  #     - helm_init:
  #         chart-repo-name: reece-ecomm
  #         chart-repo-url: s3://reece-ecomm-chart-repo/charts
  #     - helm_validate:
  #         chart-path: ./charts/picking-core-service
  
  # deploy_to_dev:
  #   description: >
  #     Deploys the current version into the Dev environment.
  #   docker:
  #     - image: cimg/base:stable
  #   parameters:
  #     environments-repo-chart-name:
  #       type: string
  #   environment:
  #     EMAIL: morsco-support-alerts@dialexa.com
  #     GIT_AUTHOR_NAME: reece-bot
  #     GIT_COMMITTER_NAME: reece-bot
  #   steps:
  #     - checkout
  #     - github-cli/setup:
  #         token: GITHUB_TOKEN
  #         version: 2.3.0
  #     - run:
  #         name: Define release version
  #         command: |
  #           current_version() {
  #             git describe --tags | awk -F '-' '{print $1}' | cut -c2-
  #           }

  #           echo "export RELEASE_VERSION=$(current_version)" >> "$BASH_ENV"
  #     - run:
  #         name: Update Environments Repo
  #         command: |
  #           cd ../
  #           git clone https://github.com/morsco-reece/internal-environments.git
  #           cd internal-environments/internal-dev
  #           set +H
  #           sed -i "/<< parameters.environments-repo-chart-name >>/!b;n;c\ \ \ \ version: \"$RELEASE_VERSION\"" Chart.yaml
  #           git add .
  #           git commit -m "<< parameters.environments-repo-chart-name >> - $RELEASE_VERSION"
  #           git push
  
  sonar-cloud:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=sanghung4_SonarCloudTestRepo

commands:
  helm_init:
    description: Configure Helm
    parameters:
      chart-repo-name:
        type: string
      chart-repo-url:
        type: string
    steps:
      - run:
          name: Install Helm S3 Plugin
          command: helm plugin install https://github.com/hypnoglow/helm-s3.git
      - run:
          name: Add Reece Helm Repo
          command: helm repo add << parameters.chart-repo-name >> << parameters.chart-repo-url >>
  
  helm_validate:
    description: Validate Helm Chart
    parameters:
      chart-path:
        type: string
    steps:
      - run:
          command: cd << parameters.chart-path >> && helm dependency build
          name: Fetch Helm Dependencies
      - run:
          command: cd << parameters.chart-path >> && helm lint
          name: Lint Helm Chart

orbs:
  github-cli: circleci/github-cli@2.2.0
  # java-services: morsco-reece/java-services@1.2.0
  maven: circleci/maven@1.2.0
  aws-cli: circleci/aws-cli@1.3.0
  node: circleci/node@2.0.2
  helm: circleci/helm@1.1.2
