version: 2.1

workflows:
  single-job-lifecycle:
    jobs:
      # - maven/test:
      #     executor:
      #       name: maven/default
      #       tag: '11.0'
      # - java-services/validate_helm_chart:
      #     helm-chart-path: ./charts/wms-eclipse-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         ignore:
      #           - master
      #           - /^release-v.*/
      # - java-services/publish_release:
      #     ecr-repo: reece/wms-eclipse-service
      #     helm-chart-name: wms-eclipse-service
      #     helm-chart-path: ./charts/wms-eclipse-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         only: master
      # - java-services/publish_hotfix:
      #     ecr-repo: reece/wms-eclipse-service
      #     helm-chart-name: wms-eclipse-service
      #     helm-chart-path: ./charts/wms-eclipse-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         only: /^release-v.*/
      # - deploy_to_dev:
      #     environments-repo-chart-name: wms-eclipse-service
      #     requires:
      #       - java-services/publish_release
      #     filters:
      #       branches:
      #         only: master
      - sonar-cloud:
          context: SonarCloud
          # requires:
          #   - maven/test

jobs: 
  # deploy_to_dev:
  #   description: >
  #     Deploys the current version into the Dev environment.
  #   docker:
  #     - image: cimg/base:stable
  #   parameters:
  #     environments-repo-chart-name:
  #       type: string
  #   environment:
  #     EMAIL: morsco-support-alerts@dialexa.com
  #     GIT_AUTHOR_NAME: reece-bot
  #     GIT_COMMITTER_NAME: reece-bot
  #   steps:
  #     - checkout
  #     - github-cli/setup:
  #         token: GITHUB_TOKEN
  #         version: 2.3.0
  #     - run:
  #         name: Define release version
  #         command: |
  #           current_version() {
  #             git describe --tags | awk -F '-' '{print $1}' | cut -c2-
  #           }

  #           echo "export RELEASE_VERSION=$(current_version)" >> "$BASH_ENV"
  #     - run:
  #         name: Update Environments Repo
  #         command: |
  #           cd ../
  #           git clone https://github.com/morsco-reece/internal-environments.git
  #           cd internal-environments/internal-dev
  #           set +H
  #           sed -i "/<< parameters.environments-repo-chart-name >>/!b;n;c\ \ \ \ version: \"$RELEASE_VERSION\"" Chart.yaml
  #           git add .
  #           git commit -m "<< parameters.environments-repo-chart-name >> - $RELEASE_VERSION"
  #           git push

  sonar-cloud:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=sanghung4_SonarCloudTestRepo

orbs:
  github-cli: circleci/github-cli@2.2.0
  # java-services: morsco-reece/java-services@1.2.0
  maven: circleci/maven@1.2.0