version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
