version: 2.1

orbs:
  python: circleci/python@2.1.1
  # python-services: morsco-reece/python-services@1.1.0

workflows:
  single-job-lifecycle:
    jobs:
      # - python-services/validate_helm_chart:
      #       helm-chart-path: ./charts/post-api-service
      #       filters:
      #         branches:
      #           ignore:
      #             - main
      #             - /^release-v.*/
      # - python-services/publish_release:
      #     python-version: "3.8"
      #     ecr-repo: reece/post-api-service
      #     helm-chart-name: post-api-service
      #     helm-chart-path: ./charts/post-api-service
      #     dockerfile: ./aws/api/Dockerfile
      #     filters:
      #       branches:
      #         only: main
      # - python-services/publish_hotfix:
      #     python-version: "3.8"
      #     ecr-repo: reece/post-api-service
      #     helm-chart-name: post-api-service
      #     helm-chart-path: ./charts/post-api-service
      #     dockerfile: ./aws/api/Dockerfile
      #     filters:
      #       branches:
      #         only: /^release-v.*/
      # - python-services/deploy_release_dev:
      #     environments-repo-chart-name: post-api-service
      #     requires:
      #       - python-services/publish_release
      #     filters:
      #       branches:
      #         only: main
      - sonar-cloud:
          context: SonarCloud

jobs:
  sonar-cloud:
    docker:
      - image: 'cimg/node:20.3.0'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - scan:
          sonar_token_variable_name: SONAR_TOKEN

commands:
  scan:
    description: Detect bugs and vulnerabilities
    parameters:
        cache_version:
            default: 1
            type: integer
        project_root:
            default: .
            type: string
        sonar_token_variable_name:
            default: SONAR_TOKEN
            type: env_var_name
    steps:
      - run:
          command: mkdir -p /tmp/cache/scanner
          name: Create cache directory if it doesn't exist
      - restore_cache:
          keys:
              - v<<parameters.cache_version>>-sonarcloud-scanner-4.7.0.2747
      - run:
          command: |
              set -e
              VERSION=4.7.0.2747
              SONAR_TOKEN=$<<parameters.sonar_token_variable_name>>
              SCANNER_DIRECTORY=/tmp/cache/scanner
              export SONAR_USER_HOME=$SCANNER_DIRECTORY/.sonar
              OS="linux"
              echo $SONAR_USER_HOME

              if [[ ! -x "$SCANNER_DIRECTORY/sonar-scanner-$VERSION-$OS/bin/sonar-scanner" ]]; then
                curl -Ol https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$VERSION-$OS.zip
                unzip -qq -o sonar-scanner-cli-$VERSION-$OS.zip -d $SCANNER_DIRECTORY
              fi

              chmod +x $SCANNER_DIRECTORY/sonar-scanner-$VERSION-$OS/bin/sonar-scanner
              chmod +x $SCANNER_DIRECTORY/sonar-scanner-$VERSION-$OS/jre/bin/java

              cd <<parameters.project_root>>
              $SCANNER_DIRECTORY/sonar-scanner-$VERSION-$OS/bin/sonar-scanner
          environment:
              SONARQUBE_SCANNER_PARAMS: '{"sonar.host.url":"https://sonarcloud.io"}'
          name: SonarCloud
      - save_cache:
          paths:
            - "/tmp/cache/scanner"
          key: v<<parameters.cache_version>>-sonarcloud-scanner-4.7.0.2747