version: 2.1

workflows:
  maven_test_then_build:
    jobs:
      # - maven/test:
      #     executor:
      #       name: maven/default
      #       tag: "17.0"
      # - java-services/validate_helm_chart:
      #     helm-chart-path: ./charts/account-management-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         ignore:
      #           - master
      #           - /^release-v.*/
      # - java-services/publish_release:
      #     java-version: "17.0"
      #     ecr-repo: reece/account-management-service
      #     helm-chart-name: account-management-service
      #     helm-chart-path: ./charts/account-management-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         only: master
      # - java-services/publish_hotfix:
      #     java-version: "17.0"
      #     ecr-repo: reece/account-management-service
      #     helm-chart-name: account-management-service
      #     helm-chart-path: ./charts/account-management-service
      #     requires:
      #       - maven/test
      #     filters:
      #       branches:
      #         only: /^release-v.*/
      # - java-services/deploy_release_dev:
      #     environments-repo-chart-name: account-management-service
      #     requires:
      #       - java-services/publish_release
      #     filters:
      #       branches:
      #         only: master
      # - maven/test:
      #     name: test_coverage
      #     executor:
      #       name: maven/default
      #       tag: "17.0"
      #     command: clean test jacoco:report coveralls:report
      #     requires:
      #       - maven/test
      - sonar-cloud:
          context: SonarCloud
          # requires:
          #   - maven/test 

jobs:
  sonar-cloud:
    docker:
      - image: 'cimg/openjdk:16.0.2'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=sanghung4_SonarCloudTestRepo

orbs:
  # java-services: morsco-reece/java-services@1.2.0
  maven: circleci/maven@1.2.0
