version: 2.1

orbs:
  android: circleci/android@2.0.0
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  unit-test:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2021.10.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save test results
          command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - sonarcloud/scan

  # android-test:
  #   parameters:
  #     system-image:
  #       type: string
  #       default: system-images;android-30;google_apis;x86
  #   executor:
  #     name: android/android-machine
  #     resource-class: xlarge
  #     tag: 2021.10.1
  #   steps:
  #     - checkout
  #     - android/start-emulator-and-run-tests:
  #         test-command: ./gradlew app:coveralls
  #         system-image: << parameters.system-image >>
  #     - run:
  #         name: Save test results
  #         command: |
  #           mkdir -p ~/test-results/junit/
  #           find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
  #         when: always
  #     - store_test_results:
  #         path: ~/test-results
  #     - store_artifacts:
  #         path: ~/test-results/junit

  # release-build:
  #   executor:
  #     name: android/android-machine
  #     resource-class: xlarge
  #     tag: 2021.10.1
  #   steps:
  #     - checkout
  #     - android/restore-gradle-cache
  #     - android/restore-build-cache
  #     - run:
  #         name: Assemble release build
  #         command: |
  #           ./gradlew assembleRelease
  #     - store_artifacts:
  #         path: app/build/outputs/apk/release/app-release-unsigned.apk

  # deploy-and-distribute:
  #   parameters:
  #     buildType:
  #       type: string
  #       default: beta
  #   executor:
  #     name: android/android-machine
  #     resource-class: xlarge
  #     tag: 2021.10.1
  #   environment: 
  #     BUILD_TYPE: << parameters.buildType >>
  #   steps: 
  #     - checkout
  #     - run:
  #         command: bundle update fastlane && gem install bundler && bundle install
  #         name: configure build
  #     - run:
  #         name: "Install Firebase CLI"
  #         command: |
  #           curl -sL firebase.tools | bash
  #     - run:
  #         name: "Deploy build to Firebase"
  #         command: |
  #           bundle exec fastlane android $BUILD_TYPE firebase_token:$FIREBASE_TOKEN firebase_app_id:$FIREBASE_APP_ID github_token:$GITHUB_TOKEN

workflows:
  test-and-build:
    jobs:
      - unit-test
      # - android-test:
      #     filters:
      #       branches:
      #         ignore: 
      #           - master
      # - deploy-and-distribute:
      #     buildType: alpha
      #     requires:
      #       - unit-test
      #       - android-test
      #     filters:
      #       branches:
      #         only: 
      #           - development
      # - deploy-and-distribute:
      #     buildType: beta
      #     requires:
      #       - unit-test
      #       - android-test
      #     filters:
      #       branches:
      #         only: 
      #           - staging
      # - deploy-and-distribute:
      #     buildType: prod
      #     requires:
      #       - unit-test
      #     filters:
      #       branches:
      #         only:
      #           - master