export enum RouteNames {
  GET_STARTED = 'GetStarted',
  LOCATION_ITEMS = 'LocationItems',
  LOCATION_ITEM_DETAIL = 'LocationItemDetail',
  SCAN_PRODUCT = 'ScanProduct',
  PRODUCT_DETAIL = 'ProductDetail',
  VERIFY_COUNT = 'VerifyCount',
  SCAN_LOCATION = 'ScanLocation',
  MANUAL_LOCATION_ENTRY = 'ManualLocationEntry',
  COUNT_LOCATIONS = 'CountLocations',
  BRANCH_SUMMARIES = 'BranchSummaries',
  WRITE_INS = 'WriteIns',
  UPDATE_WRITE_IN = 'UpdateWriteIn',
  WRITE_IN_DETAIL = 'WriteInDetail',
  ERROR_LOG = 'ErrorLog',
  FOUND_PRODUCT = 'FoundProduct',
  VARIANCE_SUMMARY = 'VarianceSummary',
  VARIANCE_LOCATION_LIST = 'VarianceLocationList',
  VARIANCE_LOCATION = 'VarianceLocation',
}
