import {
  Cell,
  IdType,
  Row,
  TableInstance,
  UseRowStateLocalState
} from 'react-table';

export function mockRow<T extends object>(
  values: Record<IdType<T>, any>,
  original: T,
  state: UseRowStateLocalState<T, unknown>
): Row<T> {
  return {
    allCells: [],
    cells: [],
    values,
    getRowProps: jest.fn(),
    index: 0,
    original,
    id: '',
    subRows: [],
    isExpanded: false,
    canExpand: false,
    toggleRowExpanded: jest.fn(),
    getToggleRowExpandedProps: jest.fn(),
    depth: 0,
    isGrouped: false,
    groupByID: '',
    groupByVal: '',
    leafRows: [],
    isSelected: false,
    isSomeSelected: false,
    toggleRowSelected: jest.fn(),
    getToggleRowSelectedProps: jest.fn(),
    state,
    setState: jest.fn()
  } as Row<T>;
}

export function mockCell<T extends object>(
  value: T,
  column: IdType<T>,
  state: UseRowStateLocalState<T, unknown>
) {
  const cell: Cell<T> = {
    column: {
      id: column,
      isVisible: false,
      render: jest.fn(),
      totalLeft: 0,
      totalWidth: 0,
      getHeaderProps: jest.fn(),
      getFooterProps: jest.fn(),
      toggleHidden: jest.fn(),
      getToggleHiddenProps: jest.fn(),
      depth: 0,
      canFilter: false,
      setFilter: jest.fn(),
      filterValue: '',
      preFilteredRows: [],
      filteredRows: [],
      canGroupBy: false,
      isGrouped: false,
      groupedIndex: 0,
      toggleGroupBy: jest.fn(),
      getGroupByToggleProps: jest.fn(),
      getResizerProps: jest.fn(),
      canResize: false,
      isResizing: false,
      canSort: false,
      toggleSortBy: jest.fn(),
      getSortByToggleProps: jest.fn(),
      clearSortBy: jest.fn(),
      isSorted: false,
      sortedIndex: 0,
      isSortedDesc: false
    },
    row: mockRow(
      value as Record<IdType<T>, any>,
      value,
      {} as UseRowStateLocalState<T, unknown>
    ),
    value,
    getCellProps: jest.fn(),
    render: jest.fn(),
    isGrouped: false,
    isPlaceholder: false,
    isAggregated: false,
    state,
    setState: jest.fn()
  };
  return cell;
}

export const mockTableInstance: TableInstance = {
  state: {
    columnOrder: [],
    expanded: {},
    filters: [],
    globalFilter: null,
    groupBy: [],
    pageSize: 0,
    pageIndex: 0,
    columnResizing: {
      columnWidth: 0,
      columnWidths: 0,
      headerIdWidths: {}
    },
    selectedRowIds: {},
    rowState: {},
    sortBy: []
  },
  plugins: [],
  dispatch: jest.fn(),
  columns: [],
  allColumns: [],
  visibleColumns: [],
  headerGroups: [],
  footerGroups: [],
  headers: [],
  flatHeaders: [],
  rows: [],
  rowsById: {},
  getTableProps: jest.fn(),
  getTableBodyProps: jest.fn(),
  prepareRow: jest.fn(),
  flatRows: [],
  totalColumnsWidth: 0,
  allColumnsHidden: false,
  toggleHideColumn: jest.fn(),
  setHiddenColumns: jest.fn(),
  toggleHideAllColumns: jest.fn(),
  getToggleHideAllColumnsProps: jest.fn(),
  getHooks: jest.fn(),
  setColumnOrder: jest.fn(),
  preExpandedRows: [],
  expandedRows: [],
  expandedDepth: 0,
  isAllRowsExpanded: false,
  toggleRowExpanded: jest.fn(),
  toggleAllRowsExpanded: jest.fn(),
  preFilteredRows: [],
  preFilteredFlatRows: [],
  preFilteredRowsById: {},
  filteredRows: [],
  filteredFlatRows: [],
  filteredRowsById: {},
  setFilter: jest.fn(),
  setAllFilters: jest.fn(),
  preGlobalFilteredRows: [],
  preGlobalFilteredFlatRows: [],
  preGlobalFilteredRowsById: {},
  globalFilteredRows: [],
  globalFilteredFlatRows: [],
  globalFilteredRowsById: {},
  setGlobalFilter: jest.fn(),
  preGroupedRows: [],
  preGroupedFlatRows: [],
  preGroupedRowsById: {},
  groupedRows: [],
  groupedFlatRows: [],
  groupedRowsById: {},
  onlyGroupedFlatRows: [],
  onlyGroupedRowsById: {},
  nonGroupedFlatRows: [],
  nonGroupedRowsById: {},
  toggleGroupBy: jest.fn(),
  page: [],
  pageCount: 0,
  pageOptions: [],
  canPreviousPage: false,
  canNextPage: false,
  gotoPage: jest.fn(),
  previousPage: jest.fn(),
  nextPage: jest.fn(),
  setPageSize: jest.fn(),
  toggleRowSelected: jest.fn(),
  toggleAllRowsSelected: jest.fn(),
  getToggleAllRowsSelectedProps: jest.fn(),
  getToggleAllPageRowsSelectedProps: jest.fn(),
  isAllRowsSelected: false,
  selectedFlatRows: [],
  setRowState: jest.fn(),
  setCellState: jest.fn(),
  preSortedRows: [],
  setSortBy: jest.fn(),
  toggleSortBy: jest.fn()
};
