import { FindBranchesDocument, MileRadiusEnum } from 'generated/graphql';

const mocks = [
  {
    request: {
      query: FindBranchesDocument,
      variables: {
        branchSearch: {
          latitude: 32.972,
          longitude: -96.7914,
          count: 100,
          isStoreFinder: true,
          branchSearchRadius: MileRadiusEnum.Miles_25
        }
      }
    },
    result: {
      data: {
        branchSearch: {
          latitude: 32.972,
          longitude: -96.7914,
          branches: [
            {
              actingBranchManager: 'C.R. Kirby ',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '817-659-3953',
              address1: '15850 Dallas Parkway',
              address2: 'Suite 105',
              branchId: '1149',
              businessHours: 'M-F: 7:00am - 5:00pm',
              city: 'Dallas',
              distance: 1.7589941,
              entityId: '546983',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: false,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.9643304,
              longitude: -96.8202783,
              name: 'Morrison Supply',
              phone: '(469) 680-3291',
              state: 'Texas',
              website: 'https://www.morrisonsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75248',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Boyd Garton',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '+1 (682) 7305002',
              address1: '1331 E. Plano Parkway',
              address2: 'Suite A',
              branchId: '1148',
              businessHours: 'M-F: 7:00am - 5:00pm',
              city: 'Plano',
              distance: 6.1380486,
              entityId: '551486',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: true,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 33.0080001,
              longitude: -96.694724,
              name: 'MORSCO HVAC Supply',
              phone: '(972)309-0521',
              state: 'Texas',
              website: 'https://www.morscohvacsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75074',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Jesse Reyes',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '+1 (972) 5053457',
              address1: '1331 E. Plano Parkway, Suite A',
              address2: 'Suite A',
              branchId: '1033',
              businessHours: 'M-F: 6:30am - 5:00pm; Sat: 7:00am - 12:00pm',
              city: 'Plano',
              distance: 6.1380486,
              entityId: '35',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: true,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 33.0080001,
              longitude: -96.694724,
              name: 'Morrison Supply',
              phone: '(972) 309-0521',
              state: 'Texas',
              website: 'https://www.morrisonsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75074',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Jason Haney',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '469-990-5213',
              address1: '1402 Dunn Dr.',
              address2: null,
              branchId: '1020',
              businessHours: 'M-F: 7:00am - 5:00pm',
              city: 'Carrollton',
              distance: 7.40009,
              entityId: '22',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: true,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.9489168,
              longitude: -96.9157984,
              name: 'MORSCO HVAC Supply',
              phone: '(972) 242-0202',
              state: 'Texas',
              website: 'https://www.morscohvacsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75006',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Kevin Pegoraro',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '+1 (817) 4844626',
              address1: '2901 Trade Center',
              address2: null,
              branchId: '1003',
              businessHours: 'M-F: 7:00am - 5:00pm; Sat: 7:00am - 12:00pm',
              city: 'Carrollton',
              distance: 8.386709,
              entityId: '5',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: false,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.989917,
              longitude: -96.934219,
              name: 'Morrison Supply',
              phone: '(972) 466-0002',
              state: 'Texas',
              website: 'https://www.morrisonsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75007',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Gregg Mitchell',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '817-240-0841',
              address1: '3200 Irving Blvd.',
              address2: 'Suite A',
              branchId: '1105',
              businessHours: 'M-F: 7:00am - 5:00pm',
              city: 'Dallas',
              distance: 12.26804,
              entityId: '107',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: false,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.8067154,
              longitude: -96.86978549999999,
              name: 'Morrison Supply',
              phone: '(469) 804-0643',
              state: 'Texas',
              website: 'https://www.morrisonsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75247',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'James Avrit',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '469-394-5257',
              address1: '1500 Dragon St., Suite B',
              address2: 'Suite B',
              branchId: '1106',
              businessHours: 'M-F: 9:00am - 5:00pm',
              city: 'Dallas',
              distance: 12.476703,
              entityId: '108',
              erpSystemName: 'ECLIPSE',
              isBandK: true,
              isHvac: false,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.7925179,
              longitude: -96.8196088,
              name: 'Expressions Home Gallery',
              phone: '(972) 432-4972',
              state: 'Texas',
              website: 'https://www.expressionshomegallery.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75207',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Rachana Patel',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '682-816-7270',
              address1: '325 Commerce Street',
              address2: 'Ste 100',
              branchId: '1083',
              businessHours: 'M-F: 9:00am - 5:00pm',
              city: 'Southlake',
              distance: 18.335812,
              entityId: '85',
              erpSystemName: 'ECLIPSE',
              isBandK: true,
              isHvac: false,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.936333,
              longitude: -97.1041441,
              name: 'Expressions Home Gallery',
              phone: '(682) 651-4000',
              state: 'Texas',
              website: 'https://www.expressionshomegallery.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '76092',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Ruben Cruz',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '(214) 277-4284',
              address1: '600 Hays Road; Bldg B',
              address2: null,
              branchId: '6040',
              businessHours: null,
              city: 'Prosper',
              distance: 18.61678,
              entityId: '40',
              erpSystemName: 'MINCRON',
              isBandK: false,
              isHvac: false,
              isPlumbing: false,
              isWaterworks: true,
              latitude: 33.2420796,
              longitude: -96.78432699999999,
              name: 'Fortiline Waterworks',
              phone: '(972) 347-4421',
              state: 'TX',
              website: 'https://www.fortiline.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75078',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Jose Cuellar',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '(214) 288-6999',
              address1: '11200 Seagoville Road',
              address2: null,
              branchId: '6021',
              businessHours: 'Coming Soon',
              city: 'Balch Springs',
              distance: 20.554827,
              entityId: '21',
              erpSystemName: 'MINCRON',
              isBandK: false,
              isHvac: false,
              isPlumbing: false,
              isWaterworks: true,
              latitude: 32.7044789,
              longitude: -96.6351273,
              name: 'Fortiline Waterworks',
              phone: '(214) 660-3662',
              state: 'TX',
              website: 'https://www.fortiline.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75180',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Collin Schmucker',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '+1 (682) 7305002',
              address1: '2040 Kristy Lane',
              address2: null,
              branchId: '1152',
              businessHours: 'M-F: 7:00am - 5:00pm',
              city: 'Rockwall',
              distance: 20.852339,
              entityId: '658646',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: true,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.9107277,
              longitude: -96.43997309999999,
              name: 'MORSCO HVAC Supply',
              phone: '(469) 433-0002',
              state: 'Texas',
              website: 'https://www.morscohvacsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75032',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Colin Bowling',
              actingBranchManagerEmail: 'seth+reecebranchmanager@dialexa.com',
              actingBranchManagerPhone: '480-287-6435',
              address1: '2040 Kristy Ln.',
              address2: null,
              branchId: '1064',
              businessHours: 'M-F: 7:00am - 5:00pm',
              city: 'Rockwall',
              distance: 20.852339,
              entityId: '66',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: false,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.9107277,
              longitude: -96.43997309999999,
              name: 'Morrison Supply',
              phone: '(469) 433-0002',
              state: 'Texas',
              website: 'https://www.morrisonsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75087',
              __typename: 'Branch'
            },
            {
              actingBranchManager: 'Min Kwon',
              actingBranchManagerEmail: 'minbaekwon@slp.com',
              actingBranchManagerPhone: '626-555-1523',
              address1: '107 Bennet Ln',
              address2: '',
              branchId: '1064',
              businessHours: 'M-F: 7:00am - 5:00pm',
              city: 'Rockwall',
              distance: 20.852339,
              entityId: '66',
              erpSystemName: 'ECLIPSE',
              isBandK: false,
              isHvac: false,
              isPlumbing: true,
              isWaterworks: false,
              latitude: 32.9107277,
              longitude: -96.43997309999999,
              name: 'Morrison Supply',
              phone: '(469) 433-0002',
              state: 'Texas',
              website: 'https://www.morrisonsupply.com',
              workdayId: null,
              workdayLocationName: null,
              zip: '75087',
              __typename: 'Branch'
            }
          ],
          __typename: 'BranchSearchResult'
        }
      }
    }
  }
];

export default mocks;
