$RNFirebaseAsStaticFramework = true
$FirebaseSDKVersion = '10.5.0'
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'branchinventory' do
  use_frameworks! :linkage => :static
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  use_expo_modules!
  config = use_native_modules!
  
  pod 'OktaOidc'

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'branchinventoryTests' do
    use_frameworks! :linkage => :static
    inherit! :complete
    # Pods for testing
    pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
