package com.reece.platform.eclipse.model.DTO;

import java.util.HashMap;
import java.util.Map;

public class WebShipViaMapping {
    public static final Map<String, String> map = new HashMap<String, String>() {{
		put("ACCT", "OUR_TRUCK");
		put("BID", "OUR_TRUCK");
		put("CORP", "OUR_TRUCK");
		put("FRI", "OUR_TRUCK");
		put("FRIA", "OUR_TRUCK");
		put("FRIP", "OUR_TRUCK");
		put("FS", "OUR_TRUCK");
		put("LBL", "OUR_TRUCK");
		put("MC", "OUR_TRUCK");
		put("MON", "OUR_TRUCK");
		put("MONA", "OUR_TRUCK");
		put("MONP", "OUR_TRUCK");
		put("ODD", "OUR_TRUCK");
		put("OT", "OUR_TRUCK");
		put("OT H", "OUR_TRUCK");
		put("OT P", "OUR_TRUCK");
		put("OT S", "OUR_TRUCK");
		put("OT U", "OUR_TRUCK");
		put("OTA", "OUR_TRUCK");
		put("OTAM", "OUR_TRUCK");
		put("OTC", "OUR_TRUCK");
		put("OTE", "OUR_TRUCK");
		put("OTHH", "OUR_TRUCK");
		put("OTI", "OUR_TRUCK");
		put("OTPD", "OUR_TRUCK");
		put("OTPM", "OUR_TRUCK");
		put("OTZ", "OUR_TRUCK");
		put("REDI", "OUR_TRUCK");
		put("RENT", "OUR_TRUCK");
		put("ROT", "OUR_TRUCK");
		put("RSLM", "OUR_TRUCK");
		put("SLSP", "OUR_TRUCK");
		put("SSI", "OUR_TRUCK");
		put("ST", "OUR_TRUCK");
		put("STI", "OUR_TRUCK");
		put("THU", "OUR_TRUCK");
		put("THUA", "OUR_TRUCK");
		put("THUP", "OUR_TRUCK");
		put("TUE", "OUR_TRUCK");
		put("TUEA", "OUR_TRUCK");
		put("TUEP", "OUR_TRUCK");
		put("WATR", "OUR_TRUCK");
		put("WED", "OUR_TRUCK");
		put("WEDA", "OUR_TRUCK");
		put("WEDP", "OUR_TRUCK");
		put("WEST", "OUR_TRUCK");
		put("XFER", "OUR_TRUCK");
		put("XFPK", "OUR_TRUCK");
		put("XHOT", "OUR_TRUCK");
		put("Z10", "OUR_TRUCK");
		put("Z11", "OUR_TRUCK");
		put("Z12", "OUR_TRUCK");
		put("Z2", "OUR_TRUCK");
		put("Z20", "OUR_TRUCK");
		put("Z23", "OUR_TRUCK");
		put("Z24", "OUR_TRUCK");
		put("Z3", "OUR_TRUCK");
		put("Z30", "OUR_TRUCK");
		put("Z34", "OUR_TRUCK");
		put("Z35", "OUR_TRUCK");
		put("Z4", "OUR_TRUCK");
		put("Z40", "OUR_TRUCK");
		put("Z5", "OUR_TRUCK");
		put("Z6", "OUR_TRUCK");
		put("Z7", "OUR_TRUCK");
		put("Z8", "OUR_TRUCK");
		put("Z9", "OUR_TRUCK");
		put("AACT", "THIRD_PARTY");
		put("ACCP", "THIRD_PARTY");
		put("ADWC", "THIRD_PARTY");
		put("BEA", "THIRD_PARTY");
		put("BUS", "THIRD_PARTY");
		put("BW", "THIRD_PARTY");
		put("CFT", "THIRD_PARTY");
		put("CMCA", "THIRD_PARTY");
		put("CONT", "THIRD_PARTY");
		put("COUR", "THIRD_PARTY");
		put("DCSG", "THIRD_PARTY");
		put("DIR", "THIRD_PARTY");
		put("DLSV", "THIRD_PARTY");
		put("EAST", "THIRD_PARTY");
		put("EXPB", "THIRD_PARTY");
		put("EXPS", "THIRD_PARTY");
		put("FB", "THIRD_PARTY");
		put("FEDX", "THIRD_PARTY");
		put("JPI", "THIRD_PARTY");
		put("KHFP", "THIRD_PARTY");
		put("LTL", "THIRD_PARTY");
		put("SEFL", "THIRD_PARTY");
		put("TL", "THIRD_PARTY");
		put("UP2A", "THIRD_PARTY");
		put("UP2D", "THIRD_PARTY");
		put("UP3D", "THIRD_PARTY");
		put("UPAS", "THIRD_PARTY");
		put("UPEA", "THIRD_PARTY");
		put("UPGR", "THIRD_PARTY");
		put("UPND", "THIRD_PARTY");
		put("UPS", "THIRD_PARTY");
		put("UPS2", "THIRD_PARTY");
		put("UPSA", "THIRD_PARTY");
		put("UPSC", "THIRD_PARTY");
		put("UPSD", "THIRD_PARTY");
		put("UPSS", "THIRD_PARTY");
		put("USPS", "THIRD_PARTY");
		put("VDR", "THIRD_PARTY");
		put("VF", "THIRD_PARTY");
		put("YRC", "THIRD_PARTY");
		put("DCWC", "WILL_CALL");
		put("IHWC", "WILL_CALL");
		put("PK", "WILL_CALL");
		put("PK H", "WILL_CALL");
		put("PK P", "WILL_CALL");
		put("PK U", "WILL_CALL");
		put("PKNH", "WILL_CALL");
		put("PKNP", "WILL_CALL");
		put("PKNR", "WILL_CALL");
		put("PKNW", "WILL_CALL");
		put("POA", "WILL_CALL");
		put("QP", "WILL_CALL");
		put("RWC", "WILL_CALL");
		put("WC", "WILL_CALL");
		put("WC H", "WILL_CALL");
		put("WC P", "WILL_CALL");
		put("WC S", "WILL_CALL");
		put("WC U", "WILL_CALL");
		put("WCH", "WILL_CALL");
		put("WCI", "WILL_CALL");
    }};
}
