export type MockBranch = {
  branchId: string;
  name?: string;
  address1?: string;
  city?: string;
  state?: string;
  zip?: string;
  isPlumbing: boolean;
  isWaterworks: boolean;
  isHvac: boolean;
  isBandK: boolean;
  isDisplayed: boolean;
};

export const mockBranches: MockBranch[] = [
  {
    branchId: 'be278a62-5f29-479c-8adc-a24fdc0b6262',
    name: 'Wolf Group',
    address1: '7 Boyd Pass',
    city: 'Mobile',
    state: 'Alabama',
    zip: '36605',
    isPlumbing: true,
    isWaterworks: false,
    isHvac: true,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: '71e82ab4-1591-45bb-8e45-8ad9c11e8807',
    name: 'Wuckert-Sauer',
    address1: '06026 Ryan Lane',
    city: 'Pensacola',
    state: 'Florida',
    zip: '32511',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: 'aa177858-a974-4793-a09b-b8706174c173',
    name: 'Lehner-Koss',
    address1: '0 Saint Paul Circle',
    city: 'Jamaica',
    state: 'New York',
    zip: '11431',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: true,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: 'ef1df19c-860f-433b-b153-abd4a3c8e8a8',
    name: 'Steuber-Hills',
    address1: '43 Canary Circle',
    city: 'Las Vegas',
    state: 'Nevada',
    zip: '89135',
    isPlumbing: true,
    isWaterworks: false,
    isHvac: true,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: '62906e9e-5981-43dd-a4cd-ed4f124b603f',
    name: 'Cole Inc',
    address1: '54831 Barnett Place',
    city: 'Lincoln',
    state: 'Nebraska',
    zip: '68531',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '0e4d27c9-9d21-47ea-8342-2af098e6c5f0',
    name: 'Schaefer and Sons',
    address1: '37 Waxwing Way',
    city: 'Jackson',
    state: 'Mississippi',
    zip: '39296',
    isPlumbing: true,
    isWaterworks: false,
    isHvac: false,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: '3549db16-7445-4a8b-8592-6c4e94d8d5fe',
    name: 'Hayes, Cummerata and Moore',
    address1: '0 Summit Park',
    city: 'Cincinnati',
    state: 'Ohio',
    zip: '45254',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: true,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: 'ee0af47d-fb68-447b-83de-0a34ee5d4937',
    name: 'Turner-Batz',
    address1: '93887 Arapahoe Center',
    city: 'Lansing',
    state: 'Michigan',
    zip: '48901',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '02082bcd-9ad9-48b0-be49-5c6bc3262e4e',
    name: 'Batz, Baumbach and Cronin',
    address1: '3 Mayfield Street',
    city: 'Greeley',
    state: 'Colorado',
    zip: '80638',
    isPlumbing: true,
    isWaterworks: false,
    isHvac: false,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: 'a02251af-8e18-4d64-ba44-31e8264ebd23',
    name: 'Stracke, Bernier and Kozey',
    address1: '7297 Bonner Avenue',
    city: 'Houston',
    state: 'Texas',
    zip: '77266',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: 'e611b414-1caf-4181-a256-e516388a41c6',
    name: "Hudson, Morissette and D'Amore",
    address1: '5495 Petterle Drive',
    city: 'Elizabeth',
    state: 'New Jersey',
    zip: '07208',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: false,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: '157cd63b-07ff-4651-b227-2f3224e962bd',
    name: 'Shields, Kuhic and Ritchie',
    address1: '7677 Pennsylvania Trail',
    city: 'Canton',
    state: 'Ohio',
    zip: '44720',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: false,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: 'f281adfe-84a2-431f-90e5-23f0b906c991',
    name: 'Beer LLC',
    address1: '6581 Schmedeman Pass',
    city: 'Albuquerque',
    state: 'New Mexico',
    zip: '87105',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: '575472c8-e189-441e-bdcd-5b3c8e0cd534',
    name: 'Walter, Hagenes and Donnelly',
    address1: '08928 Summerview Street',
    city: 'Richmond',
    state: 'Virginia',
    zip: '23225',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: '525828af-baac-4b90-92c0-a286e3afef42',
    name: 'Turcotte, Weimann and Willms',
    address1: '25883 Mcguire Hill',
    city: 'Columbus',
    state: 'Ohio',
    zip: '43268',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: '36192918-6869-47ed-b69c-aab2bc3b4059',
    name: 'Heidenreich, Labadie and Tromp',
    address1: '5 Kinsman Pass',
    city: 'Bronx',
    state: 'New York',
    zip: '10469',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: true,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '7edbabcd-cb20-44e4-b6e4-3f478a7cea01',
    name: 'Abshire, Maggio and Sawayn',
    address1: '6010 Caliangt Crossing',
    city: 'Detroit',
    state: 'Michigan',
    zip: '48211',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '17123d3a-7b80-469b-83dc-f4a5c60b3d0c',
    name: 'Grady, Murazik and Medhurst',
    address1: '608 Burning Wood Parkway',
    city: 'Las Vegas',
    state: 'Nevada',
    zip: '89166',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '2ef24272-cc03-4836-bcaf-c702d6a9a35b',
    name: 'Jacobson Inc',
    address1: '41074 Macpherson Drive',
    city: 'San Francisco',
    state: 'California',
    zip: '94177',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: '95b756ff-4955-4e96-a3b4-44ed2bfe0492',
    name: 'Fritsch-Kuhlman',
    address1: '69 Washington Lane',
    city: 'Nashville',
    state: 'Tennessee',
    zip: '37215',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: true,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '7b27eeb1-0577-4d4a-bbd1-ac0e9719994e',
    name: 'Heaney-McClure',
    address1: '01 Anhalt Junction',
    city: 'Saint Petersburg',
    state: 'Florida',
    zip: '33737',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: 'a73a2263-f692-4fe9-81e9-053a7b6526a1',
    name: 'Beahan and Sons',
    address1: '950 Claremont Court',
    city: 'Dallas',
    state: 'Texas',
    zip: '75367',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: true,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: '43c89c7c-d91c-4756-9549-98492a4c5691',
    name: 'Gulgowski Group',
    address1: '731 Ronald Regan Pass',
    city: 'Richmond',
    state: 'Virginia',
    zip: '23260',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '32b82357-c7ee-4a09-bee2-a9300e64e0d2',
    name: 'Harris, Harris and Sipes',
    address1: '1503 Toban Alley',
    city: 'Albany',
    state: 'New York',
    zip: '12262',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: true,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: 'a084cf68-829a-42cf-9654-d46b2511f7a1',
    name: 'Effertz Inc',
    address1: '0 Fairfield Court',
    city: 'Roanoke',
    state: 'Virginia',
    zip: '24009',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: false,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: 'cfbe9822-f34c-425d-bf1d-6feeb69a96fb',
    name: 'Wintheiser-Purdy',
    address1: '8532 Weeping Birch Crossing',
    city: 'Kansas City',
    state: 'Missouri',
    zip: '64114',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: '1bde0111-8c18-431e-96fb-d9744d617f2a',
    name: 'Hane-Kautzer',
    address1: '70 Upham Point',
    city: 'El Paso',
    state: 'Texas',
    zip: '79945',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: false,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: '197a25ce-73e5-4b26-9e9e-dbd86ea5eee1',
    name: "O'Conner, Walsh and Batz",
    address1: '9992 Oriole Alley',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    zip: '19093',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: '25f59fd4-e760-4083-86e8-53fbd35cb35b',
    name: 'West-Ebert',
    address1: '560 Aberg Avenue',
    city: 'Washington',
    state: 'District of Columbia',
    zip: '20551',
    isPlumbing: true,
    isWaterworks: false,
    isHvac: false,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: '54ddd63a-b473-44a6-9150-65b83a060f0a',
    name: 'Rolfson-Wilderman',
    address1: '4 Jana Park',
    city: 'Galveston',
    state: 'Texas',
    zip: '77554',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: true,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: '3c26061f-6a74-4b5b-bc7d-686ac75dbbd4',
    name: 'Erdman and Sons',
    address1: '8409 Bobwhite Terrace',
    city: 'Fort Lauderdale',
    state: 'Florida',
    zip: '33310',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: 'd0dc4599-b3ff-40ae-995d-12ca9610caf6',
    name: 'Kihn LLC',
    address1: '67102 8th Point',
    city: 'New York City',
    state: 'New York',
    zip: '10184',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: true,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: 'dae8a2c3-9b95-4048-8e7c-48d1221dbaf6',
    name: 'Kunze, Klocko and Schuppe',
    address1: '91 Kedzie Road',
    city: 'Lexington',
    state: 'Kentucky',
    zip: '40515',
    isPlumbing: true,
    isWaterworks: false,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '6872397c-6954-49ee-b131-ed826e22c77f',
    name: 'Yost-Frami',
    address1: '30 Hanover Street',
    city: 'Tulsa',
    state: 'Oklahoma',
    zip: '74184',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: 'd9588007-91c9-4b06-819c-ca5cb1561e5a',
    name: 'Treutel, Becker and Quigley',
    address1: '926 Reindahl Circle',
    city: 'New Orleans',
    state: 'Louisiana',
    zip: '70149',
    isPlumbing: true,
    isWaterworks: false,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: 'efc2f1ed-ace7-4e75-a6ad-e485406e7fd6',
    name: "D'Amore Group",
    address1: '9091 Ridgeview Place',
    city: 'Rochester',
    state: 'New York',
    zip: '14652',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: 'a57e29ce-2560-452a-89f9-00bc505b01e7',
    name: 'Streich-Torphy',
    address1: '72 Little Fleur Center',
    city: 'San Francisco',
    state: 'California',
    zip: '94121',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: false,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: 'cbff3c22-35cb-4833-ae43-3b945e20f7be',
    name: 'Carter-Schaefer',
    address1: '45 Kingsford Place',
    city: 'Tacoma',
    state: 'Washington',
    zip: '98464',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: '91b356b6-df04-48c2-b00a-30eb3f55526a',
    name: 'Crona-Larson',
    address1: '88186 Summer Ridge Court',
    city: 'Austin',
    state: 'Texas',
    zip: '78732',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: false,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: '87ecfc52-23c9-4c0b-85ae-16a6cd90873a',
    name: 'Altenwerth-Hoeger',
    address1: '41361 Dixon Plaza',
    city: 'Jackson',
    state: 'Mississippi',
    zip: '39216',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: false,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: 'c2fbea5b-8521-434c-8ecd-8b920197a940',
    name: 'Jacobi Group',
    address1: '52214 Monument Hill',
    city: 'Milwaukee',
    state: 'Wisconsin',
    zip: '53263',
    isPlumbing: true,
    isWaterworks: true,
    isHvac: true,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: 'ef952ab3-862d-4485-8734-1cd99ab2fd4a',
    name: 'Schneider and Sons',
    address1: '3 Superior Crossing',
    city: 'Chicago',
    state: 'Illinois',
    zip: '60669',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: '610ad58c-6ea4-4fa4-a4b1-a0f9205e2bf6',
    name: 'Emard-Hagenes',
    address1: '1323 Di Loreto Park',
    city: 'Mesa',
    state: 'Arizona',
    zip: '85210',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: 'bb6dbfc6-a25f-45ee-9dd4-c7857c435478',
    name: 'Green LLC',
    address1: '1089 Golf Course Circle',
    city: 'Berkeley',
    state: 'California',
    zip: '94705',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: false,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: '91511b52-9841-4d67-b51a-c37e0d7c320d',
    name: 'Collins Inc',
    address1: '229 Thackeray Alley',
    city: 'Anchorage',
    state: 'Alaska',
    zip: '99507',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: false,
    isBandK: true,
    isDisplayed: false
  },
  {
    branchId: '81a1d846-1a4d-42f6-935d-831266afd261',
    name: 'Powlowski Group',
    address1: '7 Clarendon Hill',
    city: 'Fresno',
    state: 'California',
    zip: '93762',
    isPlumbing: true,
    isWaterworks: false,
    isHvac: false,
    isBandK: false,
    isDisplayed: false
  },
  {
    branchId: 'ef9fbfab-e0ea-441c-b47d-f0e94f9296fd',
    name: 'Dickinson, Sanford and Hickle',
    address1: '469 Goodland Plaza',
    city: 'Columbia',
    state: 'Missouri',
    zip: '65211',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: '35324cc6-0c20-44c1-9d22-4de80d33c8a9',
    name: 'Nolan-Cartwright',
    address1: '2093 Sachs Terrace',
    city: 'Young America',
    state: 'Minnesota',
    zip: '55557',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: true,
    isBandK: true,
    isDisplayed: true
  },
  {
    branchId: 'a1455b85-9657-47ad-8e3f-1f9a775df55d',
    name: 'Bode, Weber and Wilkinson',
    address1: '3328 Hauk Road',
    city: 'Greensboro',
    state: 'North Carolina',
    zip: '27499',
    isPlumbing: false,
    isWaterworks: true,
    isHvac: true,
    isBandK: false,
    isDisplayed: true
  },
  {
    branchId: '0c9348fa-0370-467b-b6f3-b0336127495d',
    name: 'Emard-Mertz',
    address1: '65 Katie Hill',
    city: 'San Jose',
    state: 'California',
    zip: '95133',
    isPlumbing: false,
    isWaterworks: false,
    isHvac: false,
    isBandK: true,
    isDisplayed: false
  }
];
