#!/bin/sh

# ci-scripts/ci-hotfix-version: prints the current version number as defined in
#                               pom.xml

set -e

cd "$(dirname "$0")/.."

git describe --tags | awk -F '-' '{print $1}' | cut -c2-
