#!/bin/sh

set -e

if [ -z ${APP_NAME+x} ]; then
    echo "APP_NAME must be set"
    exit 1
fi

if [ -z ${RELEASE_VERSION+x} ]; then
    echo "RELEASE_VERSION must be set"
    exit 1
fi

if [ -z ${ORG+x} ]; then
    echo "ORG must be set"
    exit 1
fi

sed -i -e "s/version:.*/version: $RELEASE_VERSION/" Chart.yaml
sed -i -e "s/repository: .*/repository: $AWS_ECR_ACCOUNT_URL\/$ORG\/$APP_NAME/" values.yaml
sed -i -e "s/tag: .*/tag: $RELEASE_VERSION/" values.yaml

rm -rf charts
rm -rf ${APP_NAME}*.tgz