#!/bin/sh

previous_version () {
    gh release list -L 1 | awk '{print $1}' | cut -c2-
}

new_version () {
    PREVIOUS_VERSION="$(previous_version)"
    [ -z "$PREVIOUS_VERSION" ] && PREVIOUS_VERSION="0.0.0"
    PATCH_VERSION="$(echo "$PREVIOUS_VERSION" | rev | cut -d'.' -f1 | rev)"
    NEW_PATCH_VERSION="$((PATCH_VERSION + 1))"
    echo "$(echo $PREVIOUS_VERSION | rev | cut -f 2- -d . | rev).$NEW_PATCH_VERSION"
}

new_version
