#!/bin/sh

# ci-scripts/ci-rekease-version: generates a new version number by incrementing
#                                the minor number.

set -e

cd "$(dirname "$0")/.."

PREVIOUS_VERSION="$(ci-scripts/ci-current-version)"

[ -z "$PREVIOUS_VERSION" ] && PREVIOUS_VERSION="0.0.0"

MINOR_VERSION="$(echo "$PREVIOUS_VERSION" | rev | cut -d'.' -f2 | rev)"
MAJOR_VERSION="$(echo "$PREVIOUS_VERSION" | rev | cut -d'.' -f3 | rev)"

NEW_MINOR_VERSION="$((MINOR_VERSION + 1))"

echo "$MAJOR_VERSION.$NEW_MINOR_VERSION.0"
