/*
 * Eclipse API Developer Documentation
 * This documentation provides a list of API endpoints provided in this release as well as examples for using the various API endpoints
 *
 * OpenAPI spec version: 9.1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.reece.platform.eclipse.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;
import javax.validation.constraints.*;

/**
 * Object representing an Eclipse WarehouseTotePackage.
 */
@Schema(description = "Object representing an Eclipse WarehouseTotePackage.")
public class WarehouseTotePackage {

    @JsonProperty("packageType")
    private String packageType = null;

    @JsonProperty("packageQuantity")
    private Integer packageQuantity = null;

    public WarehouseTotePackage packageType(String packageType) {
        this.packageType = packageType;
        return this;
    }

    /**
     * Package Type
     * @return packageType
     **/
    @Schema(description = "Package Type")
    public String getPackageType() {
        return packageType;
    }

    public void setPackageType(String packageType) {
        this.packageType = packageType;
    }

    public WarehouseTotePackage packageQuantity(Integer packageQuantity) {
        this.packageQuantity = packageQuantity;
        return this;
    }

    /**
     * Package Count
     * minimum: 0
     * maximum: 2147483647
     * @return packageQuantity
     **/
    @Min(0)
    @Max(2147483647)
    @Schema(description = "Package Count")
    public Integer getPackageQuantity() {
        return packageQuantity;
    }

    public void setPackageQuantity(Integer packageQuantity) {
        this.packageQuantity = packageQuantity;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WarehouseTotePackage warehouseTotePackage = (WarehouseTotePackage) o;
        return (
            Objects.equals(this.packageType, warehouseTotePackage.packageType) &&
            Objects.equals(this.packageQuantity, warehouseTotePackage.packageQuantity)
        );
    }

    @Override
    public int hashCode() {
        return Objects.hash(packageType, packageQuantity);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class WarehouseTotePackage {\n");

        sb.append("    packageType: ").append(toIndentedString(packageType)).append("\n");
        sb.append("    packageQuantity: ").append(toIndentedString(packageQuantity)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
