name: QA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff poetry
        poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Analysing the code with Ruff
      run: |
        ruff check post/
    # - name: Test with pytest
    #   run: |
    #     pytest --cov post/
    # - name: update coverage
    #   id: coverage
    #   run: |
    #     coverage-badge -f -o coverage.svg
    #     git config --local user.name "kwehmeyer"
    #     git config --local user.email "kahlilwehmeyer@pm.me"
    #     git add coverage.svg
    #     git commit -m "🤖 Auto updating coverage badge"
    #   continue-on-error: true
    # - name: pushing code
    #   if: steps.coverage.outcome == 'success'
    #   run: |
    #     git fetch origin ${{ github.ref_name }}
    #     git push origin HEAD:${{ github.ref_name }}